apiVersion: v1
kind: Service
metadata:
  name: security-manager
  labels:
    app: security-manager
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    name: http
  selector:
    app: security-manager
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: security-manager-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: security-manager
    spec:
      containers:
      - name: security-manager
        image: 10.98.74.120:5000/daf-security-manager:${SECURITY_MANAGER_VERSION}
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command: ["/bin/sh", "-c", "cat /etc/extra_hosts >> /etc/hosts"]
        ports:
        - name: client
          containerPort: 9000
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: glusterfsvol
          mountPath: /opt/docker/conf/production.conf
          subPath: security-manager/conf/production.conf
          readOnly: true
        - name: glusterfsvol
          mountPath: /opt/docker/conf/logback.xml
          subPath: security-manager/conf/logback.xml
          readOnly: true
        - name: hosts
          mountPath: /etc/extra_hosts
        - name: krb5conf
          mountPath: /etc/krb5.conf
        - name: hadoopconf
          mountPath: /etc/hadoop/conf
          readOnly: true
      imagePullSecrets:
        - name: regsecret
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
      - name: hadoopconf
        hostPath:
          path: /etc/hadoop/conf
