apiVersion: v1
kind: Service
metadata:
  name: security-manager
  labels:
    app: security-manager
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    name: http
  selector:
    app: security-manager

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: security-manager-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: security-manager
    spec:
#      hostAliases:
#      - ip: "192.168.0.23"
#        hostnames:
#          - "master.platform.daf.gov.it"
#          - "master"
#      - ip: "192.168.0.22"
#        hostnames:
#         - "slave1.platform.daf.gov.it"
#          - "slave1"
#      - ip: "192.168.0.24"
#        hostnames:
#          - "slave2.platform.daf.gov.it"
#          - "slave2"
#      - ip: "192.168.0.36"
#        hostnames:
#          - "slave3.platform.daf.gov.it"
#          - "slave3"
#      - ip: "192.168.0.26"
#        hostnames:
#          - "slave4.platform.daf.gov.it"
#          - "slave4"
#      - ip: "192.168.0.26"
#        hostnames:
#          - "slave4.platform.daf.gov.it"
#          - "slave4"
#      - ip: "192.168.0.20"
#        hostnames:
#          - "edge1.platform.daf.gov.it"
#          - "edge1"
#      - ip: "192.168.0.21"
#        hostnames:
#          - "edge2.platform.daf.gov.it"
#          - "edge2"
#      - ip: "192.168.0.27"
#        hostnames:
#          - "edge3.platform.daf.gov.it"
#          - "edge3"
#      - ip: "192.168.0.29"
#        hostnames:
#          - "idm.daf.gov.it"
#          - "idm"
      containers:
      - name: security-manager
        image: nexus.daf.teamdigitale.it/daf-security-manager:2.0.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - name: client
          containerPort: 9000
        resources:
          limits:
            memory: 2548Mi
        env:
        - name: JAVA_OPTS
          value: "-server -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -Xmx2g -Xms2g -XX:MaxPermSize=1024m"
        - name: KRB5_CONFIG
          value: "/etc/extKerberosConfig/krb5.conf"
        - name: FREEIPA_ADMIN_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: freeipa_admin_pwd
        - name: PLAY_CRYPTO
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: play_crypto
        - name: MONGO_USER_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: mongo_user_pwd
        - name: PAC4J_CRYPTO
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: pac4j_crypto
        - name: SMTP_USER_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: smtp_user_pwd
        - name: LDAP_USER_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: ldap_user_pwd
        - name: CKAN_ADMIN_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: ckan_admin_pwd
        - name: SUPERSET_ADMIN_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: superset_admin_pwd
        - name: SUPERSET_OPEN_DATA_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: superset_open_data_pwd
        - name: GRAFANA_ADMIN_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: grafana_admin_pwd
        - name: KYLO_USER_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: kylo_user_pwd
        - name: IMPALA_KEYSTORE_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: impala_keyStore_pwd
        - name: IMPALA_ADMIN_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: impala_admin_pwd
        - name: HDFS_USER_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: hdfs_user_pwd
        volumeMounts:
        - name: config-volume
          mountPath: /opt/docker/conf/mnt
        - name: security-manager-logback-volume
          mountPath: /opt/docker/conf/logback.xml
          subPath: logback.xml
        - name: security-manager-cert-volume
          mountPath: /opt/docker/cert/master-impala.jks
          subPath: master-impala.jks
          readOnly: true
        - name: security-manager-cert-volume
          mountPath: /docker-java-home/jre/lib/security/jssecacerts
          subPath: jssecacerts
          readOnly: true
        - name: config-volume-kerb
          mountPath: /etc/extKerberosConfig
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: security-manager-cert-volume
        secret:
          secretName: security-manager-cert
      - name: security-manager-logback-volume
        configMap:
          name: security-manager-logback
      - name: config-volume
        configMap:
          name: security-manager-conf
      - name: config-volume-kerb
        configMap:
          name: krb5-conf
#      - name: glusterfsvol
#        persistentVolumeClaim:
#          claimName: gluster-claim
#      - name: krb5conf
#        hostPath:
#          path: /etc/krb5.conf
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "nifi"
                  operator: NotIn
                  values: ["true"]
