apiVersion: v1
kind: Service
metadata:
  name: security-manager
  labels:
    app: security-manager
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    name: http
  selector:
    app: security-manager

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: security-manager-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: security-manager
    spec:
      containers:
      - name: security-manager
        image: nexus.teamdigitale.test/daf-security-manager:1.0.1-SNAPSHOT
        #image:10.98.74.120:5000/daf-security-manager:1.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - name: client
          containerPort: 9000
        env:
        - name: JAVA_OPTS
          value: "-server -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -Xmx2g -Xms2g -XX:MaxPermSize=1024m"
        - name: FREEIPA_ADMIN_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: freeipa_admin_pwd
        - name: PLAY_CRYPTO
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: play_crypto
        - name: MONGO_USER_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: mongo_user_pwd
        - name: PAC4J_CRYPTO
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: pac4j_crypto
        - name: SMTP_USER_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: smtp_user_pwd
        - name: LDAP_USER_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: ldap_user_pwd
        - name: CKAN_ADMIN_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: ckan_admin_pwd
        - name: SUPERSET_ADMIN_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: superset_admin_pwd
        - name: GRAFANA_ADMIN_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: grafana_admin_pwd
        - name: KYLO_USER_PWD
          valueFrom:
            secretKeyRef:
              name: daf-secret
              key: kylo_user_pwd
        volumeMounts:
  #        - name: glusterfsvol
  #          mountPath: /opt/docker/conf/production.conf
  #          subPath: security-manager/conf/production.conf
        - name: config-volume
          mountPath: /opt/docker/conf/mnt
        - name: glusterfsvol
          mountPath: /opt/docker/conf/logback.conf
          subPath: security-manager/conf/logback.conf
          readOnly: true
        - name: glusterfsvol
          mountPath: /opt/docker/logs
          subPath: security-manager/logs
        - name: krb5conf
          mountPath: /etc/krb5.conf
        - name: hadoopconf
          mountPath: /etc/hadoop/conf
          readOnly: true
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: config-volume
        configMap:
          name: security-manager-conf
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
      - name: hadoopconf
        hostPath:
          path: /etc/hadoop/conf
