apiVersion: v1
kind: Service
metadata:
  name: storage-manager
  labels:
    app: storage-manager
spec:
  type: NodePort
  ports:
  - port: 9900
    protocol: TCP
    name: http
  - port: 5005
    protocol: TCP
    name: debugger
  selector:
    app: storage-manager
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: storage-manager-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: storage-manager
    spec:
      containers:
      - name: storage-manager
        image: 10.98.74.120:5000/daf-storage-manager:${STORAGE_MANAGER_VERSION}
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command: ["/bin/sh", "-c", "cat /etc/extra_hosts >> /etc/hosts"]
        ports:
        - name: client
          containerPort: 9900
        - name: debugger
          containerPort: 5005
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: glusterfsvol
          mountPath: /opt/docker/conf/production.conf
          subPath: storage-manager/conf/production.conf
          readOnly: true
        - name: glusterfsvol
          mountPath: /opt/docker/conf/logback.xml
          subPath: storage-manager/conf/logback.xml
          readOnly: true
        - name: glusterfsvol
          mountPath: /opt/docker/conf/daf.keytab
          subPath: storage-manager/conf/daf.keytab
          readOnly: true
        - name: hosts
          mountPath: /etc/extra_hosts
        - name: krb5conf
          mountPath: /etc/krb5.conf
        - name: hadoopconf
          mountPath: /etc/hadoop/conf
          readOnly: true
        - name: hbaseconf
          mountPath: /etc/hbase/conf
          readOnly: true
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
      - name: hadoopconf
        hostPath:
          path: /etc/hadoop/conf
      - name: hbaseconf
        hostPath:
          path: /etc/hbase/conf
