apiVersion: v1
kind: Service
metadata:
  name: storage-manager
  labels:
    app: storage-manager
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    name: http
  - port: 5005
    protocol: TCP
    name: debug
  selector:
    app: storage-manager
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: storage-manager-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: storage-manager
    spec:
      hostAliases:
      - ip: "192.168.0.23"
        hostnames:
          - "master.platform.daf.gov.it"
          - "master"
      - ip: "192.168.0.22"
        hostnames:
          - "slave1.platform.daf.gov.it"
          - "slave1"
      - ip: "192.168.0.24"
        hostnames:
          - "slave2.platform.daf.gov.it"
          - "slave2"
      - ip: "192.168.0.36"
        hostnames:
          - "slave3.platform.daf.gov.it"
          - "slave3"
      - ip: "192.168.0.26"
        hostnames:
          - "slave4.platform.daf.gov.it"
          - "slave4"
      - ip: "192.168.0.26"
        hostnames:
          - "slave4.platform.daf.gov.it"
          - "slave4"
      - ip: "192.168.0.20"
        hostnames:
          - "edge1.platform.daf.gov.it"
          - "edge1"
      - ip: "192.168.0.21"
        hostnames:
          - "edge2.platform.daf.gov.it"
          - "edge2"
      - ip: "192.168.0.27"
        hostnames:
          - "edge3.platform.daf.gov.it"
          - "edge3"
      - ip: "192.168.0.29"
        hostnames:
          - "idm.daf.gov.it"
          - "idm"
      containers:
      - name: storage-manager
        image: 10.98.74.120:5000/daf-storage-manager:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTS
          value: "-server -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -Xmx2g -Xms2g -XX:MaxPermSize=1024m"
        ports:
        - name: client
          containerPort: 9000
        volumeMounts:
        - name: glusterfsvol
          mountPath: /opt/docker/conf/production.conf
          subPath: storage-manager/conf/production.conf
          readOnly: true
        - name: glusterfsvol
          mountPath: /opt/docker/conf/logback.xml
          subPath: storage-manager/conf/logback.xml
          readOnly: true
        - name: glusterfsvol
          mountPath: /opt/docker/conf/daf.keytab
          subPath: storage-manager/conf/daf.keytab
          readOnly: true
        - name: krb5conf
          mountPath: /etc/krb5.conf
        - name: hadoopconf
          mountPath: /etc/hadoop/conf
          readOnly: true
        - name: hbaseconf
          mountPath: /etc/hbase/conf
          readOnly: true
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim
      - name: krb5conf
        hostPath:
          path: /etc/krb5.conf
      - name: hadoopconf
        hostPath:
          path: /etc/hadoop/conf
      - name: hbaseconf
        hostPath:
          path: /etc/hbase/conf
